!!python/object:sdfstudio.configs.base_config.Config
data: null
experiment_name: test16-fixed-bias0p1-eik0p1-80k
logging: !!python/object:sdfstudio.configs.base_config.LoggingConfig
  enable_profiler: false
  local_writer: !!python/object:sdfstudio.configs.base_config.LocalWriterConfig
    _target: !!python/name:sdfstudio.utils.writer.LocalWriter ''
    enable: true
    max_log_size: 10
    stats_to_track: !!python/tuple
    - !!python/object/apply:sdfstudio.utils.writer.EventName
      - Train Iter (time)
    - !!python/object/apply:sdfstudio.utils.writer.EventName
      - Train Rays / Sec
    - !!python/object/apply:sdfstudio.utils.writer.EventName
      - Test PSNR
    - !!python/object/apply:sdfstudio.utils.writer.EventName
      - Vis Rays / Sec
    - !!python/object/apply:sdfstudio.utils.writer.EventName
      - Test Rays / Sec
  max_buffer_size: 20
  relative_log_dir: !!python/object/apply:pathlib.PosixPath []
  steps_per_log: 10
machine: !!python/object:sdfstudio.configs.base_config.MachineConfig
  dist_url: auto
  machine_rank: 0
  num_gpus: 1
  num_machines: 1
  seed: 42
method_name: neus-facto
optimizers:
  field_background:
    optimizer: !!python/object:sdfstudio.engine.optimizers.AdamWOptimizerConfig
      _target: &id001 !!python/name:torch.optim.adamw.AdamW ''
      eps: 1.0e-15
      lr: 0.005
      weight_decay: 0.01
    scheduler: !!python/object:sdfstudio.engine.schedulers.NeuSSchedulerConfig
      _target: &id002 !!python/name:sdfstudio.engine.schedulers.NeuSScheduler ''
      learning_rate_alpha: 0.05
      max_steps: 80000
      warm_up_end: 1000
  fields:
    optimizer: !!python/object:sdfstudio.engine.optimizers.AdamWOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.005
      weight_decay: 0.01
    scheduler: !!python/object:sdfstudio.engine.schedulers.NeuSSchedulerConfig
      _target: *id002
      learning_rate_alpha: 0.05
      max_steps: 80000
      warm_up_end: 1000
  proposal_networks:
    optimizer: !!python/object:sdfstudio.engine.optimizers.AdamWOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.01
      weight_decay: 0
    scheduler: !!python/object:sdfstudio.engine.schedulers.MultiStepSchedulerConfig
      _target: !!python/name:torch.optim.lr_scheduler.MultiStepLR ''
      max_steps: 80000
output_dir: !!python/object/apply:pathlib.PosixPath
- /
- workspace
- test16-fixed-bias0p1-eik0p1-80k
- train
pipeline: !!python/object:sdfstudio.pipelines.base_pipeline.VanillaPipelineConfig
  _target: !!python/name:sdfstudio.pipelines.base_pipeline.VanillaPipeline ''
  datamanager: !!python/object:sdfstudio.data.datamanagers.base_datamanager.VanillaDataManagerConfig
    _target: !!python/name:sdfstudio.data.datamanagers.base_datamanager.VanillaDataManager ''
    camera_optimizer: !!python/object:sdfstudio.cameras.camera_optimizers.CameraOptimizerConfig
      _target: !!python/name:sdfstudio.cameras.camera_optimizers.CameraOptimizer ''
      mode: 'off'
      optimizer: !!python/object:sdfstudio.engine.optimizers.AdamWOptimizerConfig
        _target: *id001
        eps: 1.0e-08
        lr: 1.0e-05
        weight_decay: 0.0
      orientation_noise_std: 0.0
      param_group: camera_opt
      position_noise_std: 0.0
      scheduler: !!python/object:sdfstudio.engine.schedulers.SchedulerConfig
        _target: !!python/name:sdfstudio.engine.schedulers.ExponentialDecaySchedule ''
        lr_final: 1.0e-06
        max_steps: 25000
    camera_res_scale_factor: 1.0
    dataparser: !!python/object:sdfstudio.data.dataparsers.nerfstudio_dataparser.NerfstudioDataParserConfig
      _target: !!python/name:sdfstudio.data.dataparsers.nerfstudio_dataparser.Nerfstudio ''
      auto_scale_poses: median
      center_method: focus
      data: !!python/object/apply:pathlib.PosixPath
      - __CONFIG_DIR__
      - ..
      - ..
      - ..
      - ..
      downscale_factor: 1
      orientation_method: vertical
      scale_factor: 2.5
      scene_scale: 1.0
      train_split_fraction: 0.95
      use_all_train_images: false
    eval_camera_res_scale_factor: null
    eval_image_indices: !!python/tuple
    - 0
    eval_num_images_to_sample_from: -1
    eval_num_rays_per_batch: 8192
    eval_num_times_to_repeat_images: -1
    train_num_images_to_sample_from: -1
    train_num_rays_per_batch: 8192
    train_num_times_to_repeat_images: -1
  model: !!python/object:sdfstudio.models.neus_facto.NeuSFactoModelConfig
    _target: !!python/name:sdfstudio.models.neus_facto.NeuSFactoModel ''
    anneal_end: 50000
    auto_far_plane_margin: 1.2
    auto_near_far_plane: false
    auto_near_plane_margin: 0.8
    auto_near_plane_min: 0.01
    background_color: black
    background_model: mlp
    base_variance: 64
    beta_anneal_end: 0.0002
    beta_anneal_init: 0.05
    beta_anneal_max_num_iters: 1000000
    collider_params:
      far_plane: 6.0
      near_plane: 2.0
    curvature_loss_multi: 0.0
    curvature_loss_warmup_steps: 20000
    distortion_loss_mult: 0.0
    eikonal_loss_mult: 0.1
    enable_collider: true
    enable_curvature_loss_schedule: false
    enable_numerical_gradients_schedule: false
    enable_progressive_hash_encoding: false
    eval_num_rays_per_chunk: 8192
    far_plane: 5.0
    far_plane_bg: 1000.0
    fg_mask_loss_mult: 0.0
    interlevel_loss_mult: 1.0
    level_init: 4
    loss_coefficients:
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
    min_patch_variance: 0.01
    mono_depth_loss_mult: 0.0
    mono_normal_loss_mult: 0.0
    near_plane: 0.01
    num_neus_samples_per_ray: 48
    num_proposal_iterations: 2
    num_proposal_samples_per_ray: !!python/tuple
    - 256
    - 96
    num_samples: 64
    num_samples_importance: 64
    num_samples_outside: 32
    num_up_sample_steps: 4
    orientation_loss_mult: 0.0
    overwrite_near_far_plane: true
    patch_size: 11
    patch_warp_angle_thres: 0.3
    patch_warp_loss_mult: 0.0
    periodic_tvl_mult: 0.0
    perturb: true
    proposal_net_args_list:
    - hidden_dim: 16
      log2_hashmap_size: 17
      max_res: 64
      num_levels: 5
    - hidden_dim: 16
      log2_hashmap_size: 17
      max_res: 256
      num_levels: 5
    proposal_update_every: 5
    proposal_warmup: 1000
    proposal_weights_anneal_max_num_iters: 1000
    proposal_weights_anneal_slope: 10.0
    rgb_loss_type: L1
    roughness_sparsity_loss_mult: 0.0
    s3im_kernel_size: 4
    s3im_loss_mult: 0.0
    s3im_patch_height: 32
    s3im_repeat_time: 10
    s3im_stride: 4
    scene_contraction_norm: inf
    sdf_field: !!python/object:sdfstudio.fields.sdf_field.SDFFieldConfig
      _target: !!python/name:sdfstudio.fields.sdf_field.SDFField ''
      appearance_embedding_dim: 16
      base_res: 16
      beta_init: 0.3
      bias: 0.1
      divide_factor: 2.0
      enable_pred_roughness: false
      encoding_type: hash
      geo_feat_dim: 256
      geometric_init: true
      hash_features_per_level: 2
      hash_smoothstep: true
      hidden_dim: 256
      hidden_dim_color: 256
      inside_outside: false
      learned_specular_scale: false
      log2_hashmap_size: 19
      max_res: 2048
      num_layers: 2
      num_layers_color: 2
      num_levels: 16
      off_axis: false
      position_encoding_max_degree: 6
      rgb_padding: 0.001
      roughness_blend_space: encoding
      specular_exclude_geo_features: false
      use_appearance_embedding: true
      use_diffuse_color: false
      use_fresnel_term: false
      use_grid_feature: true
      use_n_dot_v: false
      use_numerical_gradients: false
      use_position_encoding: true
      use_reflections: false
      use_roughness_gated_specular: false
      use_roughness_in_color_mlp: false
      use_specular_tint: false
      weight_norm: true
    sensor_depth_freespace_loss_mult: 0.0
    sensor_depth_l1_loss_mult: 0.0
    sensor_depth_sdf_loss_mult: 0.0
    sensor_depth_truncation: 0.015
    sparse_points_sdf_loss_mult: 0.0
    steps_per_level: 10000
    topk: 4
    use_anneal_beta: false
    use_average_appearance_embedding: true
    use_proposal_weight_anneal: true
    use_same_proposal_network: false
    use_single_jitter: true
timestamp: run
trainer: !!python/object:sdfstudio.configs.base_config.TrainerConfig
  accumulate_grad_steps: 1
  load_config: null
  load_dir: null
  load_scheduler: true
  load_step: null
  max_num_iterations: 80001
  mixed_precision: true
  relative_model_dir: !!python/object/apply:pathlib.PosixPath
  - sdfstudio_models
  sanity_check: false
  save_only_latest_checkpoint: true
  steps_per_eval_all_images: 100000000
  steps_per_eval_batch: 100000000
  steps_per_eval_image: 100000000
  steps_per_save: 20000
viewer: !!python/object:sdfstudio.configs.base_config.ViewerConfig
  ip_address: 0.0.0.0
  launch_bridge_server: true
  max_num_display_images: 512
  num_rays_per_chunk: 32768
  quit_on_train_completion: false
  relative_log_filename: viewer_log_filename.txt
  start_train: true
  websocket_port: 7007
  zmq_port: null
vis: tensorboard
